/* tslint:disable */
/* eslint-disable */
/**
 * USAsset API Service
 *      USAsset API Service with Role-Based Access Control (RBAC)          ## Authentication     This API supports two authentication methods:     1. **API Key**: Use \'x-api-key\' header for basic authentication     2. **JWT Bearer Token**: Use \'Authorization: Bearer <token>\' for RBAC-protected endpoints          ## Permission System     RBAC endpoints require specific permissions in the format \'action:resource\':     - **Actions**: view, create, edit, delete     - **Resources**: project, location, asset, user          ## System Roles     - **project_admin**: Full project access (all permissions)     - **project_manager**: Manage resources (no user management)     - **engineer**: Edit assets/locations only     - **viewer**: Read-only access          ## Error Responses     - **401 Unauthorized**: Missing or invalid authentication     - **403 Forbidden**: Missing required permission     - **404 Not Found**: Resource not found   
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
