/* tslint:disable */
 
/**
 * USAsset API Service
 *      USAsset API Service with Role-Based Access Control (RBAC)          ## Authentication     This API supports two authentication methods:     1. **API Key**: Use \'x-api-key\' header for basic authentication     2. **JWT Bearer Token**: Use \'Authorization: Bearer <token>\' for RBAC-protected endpoints          ## Permission System     RBAC endpoints require specific permissions in the format \'action:resource\':     - **Actions**: view, create, edit, delete     - **Resources**: project, location, asset, user          ## System Roles     - **project_admin**: Full project access (all permissions)     - **project_manager**: Manage resources (no user management)     - **engineer**: Edit assets/locations only     - **viewer**: Read-only access          ## Error Responses     - **401 Unauthorized**: Missing or invalid authentication     - **403 Forbidden**: Missing required permission     - **404 Not Found**: Resource not found   
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

